### ISSUE TITLE
config: prettier 설정

### ISSUE THREAD

**Issue by devstefancho** [vim-kr/renewal#1]
[.prettierrc](https://prettier.io/docs/en/configuration.html) 설정
```json
{
  "trailingComma": "es5",
  "tabWidth": 4,
  "semi": true,
  "singleQuote": true
}
```

위와 같이 하려는데, 의견 부탁드립니다.

**Comment by malkoG** [comment]
당장은 커뮤니티에서 권장하는대로 디폴트인 것들 위주로 세팅해놓고, 세부적인 것들은 문제가 되면 그때 변경해도 괜찮을 것 같습니다.

**Comment by devstefancho** [comment]
넵 좋습니다! 그러면 prettier는 config에서 권장하는 그대로 하도록 하겠습니다.
semi는 Basic 예시대로 다시 false로 바꾸겠습니다.
