### ISSUE TITLE
[WEB-0] 배포환경 세팅

### ISSUE THREAD

**Issue by devstefancho** [vim-kr/renewal#6]
지속적 배포를 위한 세팅
- github page에 배포할 것인지 결정이 필요함
- vim.kr 도메인 연결 필요

**Comment by malkoG** [comment]
Github Page 배포가이드 : https://docs.astro.build/en/guides/deploy/github/

**Comment by malkoG** [comment]
closed via [a18eec9](https://github.com/vim-kr/renewal/commit/a18eec9addbec307a9bda961d3ff482c612caabe)
